docs/README.md
docs/community/stable_feature_checklist.md

This doc describes the requirements for moving
an experimental feature into stable.
Also adds a new community subdirectory and updates
the doc README.

Add community stable feature checklist

---

docs/concepts/about_canopy.md
docs/glossary/glossary.md

- Add a new "About Canopy" topic with a high-level overview of Canopy and saplings.
(Details such as how-to topics and integration patterns will be developed later.)
This initial version notes that some functionality is not yet available.
- Add "Canopy" and "sapling" to the Splinter glossary

Add Canopy overview topic and glossary definitions

---

README.md
docs/README.md
docs/index.md

The docs/index.md file is a "landing page" for the Splinter documentation
It contains links to the available Markdown-format documentation in the
splinter-docs repo. (This approach is temporary until the publishing tools and
a doc hosting site are available.)
This PR also adds links to this file from the main and docs READMEs
and updates the repo organization info in docs/README.

Add doc home page for Splinter docs

---

docs/index.md

Add a new "Reference Guides" section to the main Splinter doc page
with a link to the Splinter API Reference at https://docs.rs/splinter

Add link to Rust doc for crate splinter 

---

docs/README.md
docs/upgrading/README.md
docs/upgrading/TEMPLATE_upgrading.md
docs/upgrading/splinter-v0.3.12-from-v0.3.11.md

Note the splinter links assume that the 0.3.12 tag has been created so they will not work until the 0.3.12 release is done.

Add Upgrading doc directory and Upgrade doc for 0.3.12 from 0.3.11

---

CODEOWNERS
MAINTAINERS.md

Signed-off-by: Darian Plumb <dplumb@bitwise.io>

Add Davey Newhall as codeowner and maintainer

---

docs/upgrading/README.md
docs/upgrading/splinter-v0.3.13-from-v0.3.12.md

Add the upgrade guide for 0.3.13 from 0.3.12.  This guide includes notes
about the socket version handshake, deprecated methods, and the new
RestApiServerErrror variant.
Signed-off-by: Peter Schwarz <pschwarz@bitwise.io>

Add upgrade guide for 0.3.13

---

docs/README.md
docs/index.md
docs/references/cli/cli_command_reference.md
docs/references/cli/splinter-cert-generate.1.md

This PR adds a location for the markdown man pages that are included in the splinter cli and copies over the file for `splinter cert generate`

Add CLI Command Reference section and add splinter cert generate file

---

api/openapi.yml

Updates the OpenAPI documentation to match the latest version in the splinter repo.
This is the latest version of openapi.yml as of https://github.com/Cargill/splinter/pull/584

Update OpenAPI docs to match splinter

---

docs/howto/uploading_smart_contract.md

Updates the circuit create command to circuit propose in the "Uploading
a Smart Contract" document, since this has been changed in the Splinter
CLI.
This PR should not be merged until the corresponding change in splinter has been merged: Cargill/splinter#609

Update `circuit create` to `circuit propose`

---

docs/howto/generating_insecure_certificates_for_development.md

Update docs for the changes in Cargill/splinter#727
This should be merged after Cargill/splinter#727

Update generating cert doc for new tls options

---

docs/howto/generating_insecure_certificates_for_development.md

Updates the how to for changes introduced in
https://github.com/Cargill/splinter/pull/754
Also adds some missing options to the config print out.

Update generating cert doc for updated splinter options

---

docs/faq/faq.md

Adds an entry to the FAQ for verifying consistency of state between
scabbard services.
The contents of this PR are subject to change based on https://github.com/Cargill/splinter/pull/836 and a man page for the `scabbard state root` CLI command.

Add FAQ for checking scabbard state root hashes

---

docs/faq/faq.md
docs/index.md

Reword demo-related content in doc index and FAQ now that the Private Counter
and Private XO examples are gone (deleted from the splinter repo a while back).

Remove Private Counter + XO demos from docs

---

css/custom.css

Before, when a right sidebar link was clicked, it would
start the content at the very top of the window, behind
the header.
This commit adds css so that h2 and h3 headers that are
linked will snap into place below the header.

Update right-sidebar links to snap below the header

---

_config.yml
_layouts/0.4.html
_layouts/default.html
community/index.md
community/licensing.md
community/stable_feature_checklist.md
docs/index.md

This sets the layouts using _config.yml instead of front matter in the
md files. This is nice, in part, because it can be set on a directory
basis.
This also changes default to what was 'landing page' previously and
renames the previously 'default' layout to '0.4'.
Signed-off-by: Shawn T. Amundson <amundson@bitwise.io>

Set layouts via _config.yml file

---

docs/0.4/references/cli/cli_command_reference.md
docs/0.4/references/cli/splinter-cert-generate.1.md
docs/0.4/references/cli/splinter-cert.1.md
docs/0.4/references/cli/splinter-circuit-list.1.md
docs/0.4/references/cli/splinter-circuit-proposals.1.md
docs/0.4/references/cli/splinter-circuit-propose.1.md
docs/0.4/references/cli/splinter-circuit-show.1.md
docs/0.4/references/cli/splinter-circuit-template-arguments.1.md
docs/0.4/references/cli/splinter-circuit-template-list.1.md
docs/0.4/references/cli/splinter-circuit-template-show.1.md
docs/0.4/references/cli/splinter-circuit-template.1.md
docs/0.4/references/cli/splinter-circuit-vote.1.md
docs/0.4/references/cli/splinter-circuit.1.md
docs/0.4/references/cli/splinter-database-migrate.1.md
docs/0.4/references/cli/splinter-database.1.md
docs/0.4/references/cli/splinter-health-status.1.md
docs/0.4/references/cli/splinter-health.1.md
docs/0.4/references/cli/splinter-keygen.1.md
docs/0.4/references/cli/splinter.1.md
docs/0.4/references/cli/splinterd.1.md
justfile

This function assumes that your directory structure has
splinter and splinter-docs at the same level by default. Running
`just` or `just copy-docs` will rsync the man pages files
from splinter cli and splinterd to docs/VERSION/references/cli where
the version of the docs is taking from splinter/VERSIONS file.
The location of the splinter repo can be changed by running
`just --set splinter_repo PATH`
Also updates and adds new man pages from splinter 0-4 branch. To use this script right now requires manually updating the VERSION in the splinter repo on the 0-4 branch so it is 0.4.x instead of 0.3.19

 Add justfile for copying man pages from the splinter repo

---

docs/0.4/references/cli/cli_command_reference.md

Adds headers for each subset of commands and
remove bullets. Also adds a short description to each
command. These descriptions are from their man page.

Reformat CLI Command Reference page

---

_includes/footer.html
css/custom.css

Note: Currently the footer does not stay on the bottom for very short pages, such as the current about Biome doc.

Add initial footer for splinter website

---

docs/0.4/examples/gameroom/index.md
docs/0.5/examples/gameroom/index.md

Initially, the content duplicates splinter/examples/gameroom/README.md, with one
change: A link to the prebuilt images at hub.docker.com/u/splintercommunity

Add landing page for Gameroom example

---

_includes/scripts.html
scripts/activeLinks.js

Updates the JS code for setting the active links in the navbar and left
sidebar to account for overlapping paths. Also moves the code into a
function in its own JS script and calls the function from the `scripts`
include.

Fix active link selection

---

ci/publish-docker
justfile

"splinter.dev" is easily confused with the "splinter-dev" image used as a
base image for splinter development.

Change published docker image name

---

_includes/0.4/left_sidebar.html
_includes/0.5/left_sidebar.html
docs/0.4/howto/building_splinter.md
docs/0.5/howto/building_splinter.md

Initially, the content duplicates the "Building Splinter" section
in the splinter repo's README, with two changes:
- Added an intro sentence with a link to the splinter repo
- Fixed punctuation and parens in the last paragraph

Add Building Splinter topic to docs

---

releases/0.4/index.md

-- Add missing comma, fix link mashup, and make Splinter Software show up in the right-nav TOC
-- Add "For more information, ..." to the CLIs section, so that it's consistent with the other sections. (Move the man page info from Documentation, reword it for clarity, and add a link to the CLI reference.) This change also makes the Documentation list easier to read.

Fix typos + inconsistency in 0.4 release overview

---

_includes/scripts.html
docs/0.4/howto/planning_splinter_deployment.md
docs/0.4/index.md
docs/0.5/howto/planning_splinter_deployment.md
docs/0.5/index.md
scripts/generateRightSidebar.js

Removes the explicitly defined anchor tags from the docs index markdown
files and uses the implicit markdown links instead. This fixes some
incorrect behavior with the website.

Remove anchor tags from markdown files

---

_includes/0.4/left_sidebar.html
_includes/0.5/left_sidebar.html
docs/0.4/references/rust_api/index.md
docs/0.5/references/rust_api/index.md

This PR eliminates an external link from the left-nav TOC.
Note: The v0.5 version of the splinter and scabbard crates (and docs) aren't
being published yet, so the 0.5 doc links go to the same docs.rs location as
the 0.4 links. A later PR will be needed once the crates (and docs) are versioned.

Add landing page for the Rust API references

---

_includes/0.4/left_sidebar.html
_includes/0.5/left_sidebar.html
docs/0.4/references/api/index.md
docs/0.5/references/api/index.md

This change changes the Splinter REST API link in the left-nav TOC from an external link to a site-internal one.

Add landing page for the REST API reference

---

_includes/0.4/left_sidebar.html
_includes/0.5/left_sidebar.html
docs/0.4/concepts/biome_user_management.md
docs/0.4/concepts/canopy_application_framework.md
docs/0.4/examples/gameroom/walkthrough/index.md
docs/0.4/howto/planning_splinter_deployment.md
docs/0.5/concepts/biome_user_management.md
docs/0.5/concepts/canopy_application_framework.md
docs/0.5/examples/gameroom/walkthrough/index.md
docs/0.5/howto/planning_splinter_deployment.md
releases/0.4/index.md

Provide more specific (and helpful) topic titles:
- About Biome -> Biome User Management
- About Canopy -> Canopy Application Framework
Also update links (and add missing link) in other topics: 0.4 release overview, Gameroom walkthrough, and Planning a Splinter Deployment. These links now point to the published docs (not the markdown files in the repo) and use relative paths when possible.

Change titles of About topics

---

docs/0.4/references/cli/splinter-cert-generate.1.md
docs/0.4/references/cli/splinter-cert.1.md
docs/0.4/references/cli/splinter-circuit-list.1.md
docs/0.4/references/cli/splinter-circuit-proposals.1.md
docs/0.4/references/cli/splinter-circuit-propose.1.md
docs/0.4/references/cli/splinter-circuit-show.1.md
docs/0.4/references/cli/splinter-circuit-template-arguments.1.md
docs/0.4/references/cli/splinter-circuit-template-list.1.md
docs/0.4/references/cli/splinter-circuit-template-show.1.md
docs/0.4/references/cli/splinter-circuit-template.1.md
docs/0.4/references/cli/splinter-circuit-vote.1.md
docs/0.4/references/cli/splinter-circuit.1.md
docs/0.4/references/cli/splinter-database-migrate.1.md
docs/0.4/references/cli/splinter-database.1.md
docs/0.4/references/cli/splinter-health-status.1.md
docs/0.4/references/cli/splinter-health.1.md
docs/0.4/references/cli/splinter-keygen.1.md
docs/0.4/references/cli/splinter.1.md

This pulls the changes, specifically adding the copyright header to the
CLI man pages via the `just copy-docs` script, to the 0.4 docs as these
changes have been backported to the 0.4 branch in Splinter.

Add copyright headers to 0.4 man pages

---

_includes/releases/left_sidebar.html
css/custom.css
releases/management/artifacts.md
releases/management/versioning.md

Adds the `/releases/about.html` page that explains Splinter's release
cycle and points to all of Splinter's major published artifacts.

Add "About Releases" page 

---

_includes/0.4/left_sidebar.html
_includes/0.5/left_sidebar.html
docs/0.4/concepts/features_and_concepts.md
docs/0.4/images/diagram-splinter-circuits+3companies.svg
docs/0.4/images/diagram-splinter-smartcontractdeployment.svg
docs/0.4/images/diagram-splinter-twopartycircuit.svg
docs/0.5/concepts/features_and_concepts.md
docs/0.5/images/diagram-splinter-circuits+3companies.svg
docs/0.5/images/diagram-splinter-smartcontractdeployment.svg
docs/0.5/images/diagram-splinter-twopartycircuit.svg

This is step 1 of moving the Splinter README's "Features and Concepts" content into the Splinter docs. (The content is identical other than changing the bold phrases to subheadings and adding a missing period.)

Add "Features and Concepts" from Splinter README

---

docs/0.4/howto/planning_splinter_deployment.md
docs/0.5/howto/planning_splinter_deployment.md
releases/0.4/index.md

Removes inline ToCs that are no longer necessary because of the right
sidebar on the website.
The ToC for the docs introduction page is left in-place because it
provides a helpful summary for and transition into the body of the
document.

Remove unnecessary inline ToCs

---

_includes/0.4/left_sidebar.html
_includes/0.5/left_sidebar.html

Create a new "For Administrators" section in the left-nav TOC
and move "Planning a Splinter Deployment" to that section.

Move Planning Deployment to Admin section

---

_includes/community/left_sidebar.html
community/doc_guidelines/rust_apis.md

This commit includes a new "Doc Guidelines" section with all planned guidelines (to minimize merge conflicts). Some links will be broken until the other guideline PRs have been merged.

Add Rust API doc guidelines to Community section

---

community/planning/admin_ui.md
community/planning/features.md

The initial planning doc used the preliminary term "Admin application" and called it "an example of an application" (which is incorrect).
This PR updates the planning doc to use the same term as the Splinter doc and adds a link to the Admin UI tutorial. It also renames the file to conform with best practices (so that file name matches the doc title).

Update Admin UI term in Planning>Features doc

---

_includes/community/left_sidebar.html
community/doc_guidelines/rest_apis.md

This commit includes a new "Doc Guidelines" section with all planned guidelines (to minimize merge conflicts). Some links will be broken until the other guideline PRs have been merged.

Add REST API doc guidelines to Community section

---

_includes/community/left_sidebar.html
community/doc_guidelines/capitalization.md

This commit includes a new "Doc Guidelines" section with all planned guidelines (to minimize merge conflicts). Some links will be broken until the other guideline PRs have been merged.
Note: This file contains an internal TOC for increased usability (for those readers who don't notice or use right-nav menus).

Add Capitalization doc guidelines to Community section

---

ci/lint.dockerfile

This is a temporary workaround so work can continue while an issue in mdl
0.10.0 is addressed.

Pin mdl version

---

_includes/0.4/left_sidebar.html
_includes/0.5/left_sidebar.html
docs/0.4/concepts/security_considerations.md
docs/0.4/howto/planning_splinter_deployment.md
docs/0.5/concepts/security_considerations.md
docs/0.5/howto/planning_splinter_deployment.md

This commit also adds a link to this topic in "Planning a Splinter Deployment"
and changes the link that used to go to the Splinter doc landing page;
(it now goes to "Features and Concepts").
To test: run `docker-compose up --build`, then go to  `http://127.0.0.1:8080`.  The new topic is under "For Administrators".

Add new admin topic, Security Considerations

---

_includes/0.4/left_sidebar.html
_includes/0.5/left_sidebar.html
docs/0.4/troubleshooting/checking_state_consistency.md
docs/0.5/troubleshooting/checking_state_consistency.md

Create a new troubleshooting topic from the former FAQ's tip, "How can I tell if state is consistent across scabbard services on a circuit?"
Because this is the first troubleshooting topic, this commit also creates a `troubleshooting` subdirectory (under docs/0.4 and docs/0.5) and adds a Troubleshooting section in the doc left-nav TOC.

Add troubleshooting topic: Check State Consistency

---

examples/index.md

On the Splinter Examples page, change the Grid documentation link to go to grid.hyperledger.org/docs/ instead of the grid-docs repo.

Update Grid doc link to point to website

---

_includes/0.5/left_sidebar.html
docs/0.5/howto/using_circuit_templates.md
docs/0.5/references/cli/splinter-circuit-list.1.md
docs/0.5/references/cli/splinter-circuit-proposals.1.md
docs/0.5/references/cli/splinter-circuit-show.1.md
docs/0.5/references/cli/splinter-circuit-template-arguments.1.md
docs/0.5/references/cli/splinter-circuit-template-list.1.md
docs/0.5/references/cli/splinter-circuit-template-show.1.md
docs/0.5/references/cli/splinter-circuit-template.1.md

Adds an app-dev guide using the `circuit-template` feature in Splinter

Add circuit template how-to topic

---

docs/0.4/concepts/canopy_application_framework.md
docs/0.5/concepts/canopy_application_framework.md

Signed-off-by: JasonWalker <Jason.Walker1@aa.com>
Fix: links to `grid-ui` just needed some care.

grid-ui links for example canopy app are broken

---

ci/website.dockerfile
docker/splinter-docs-redoc

The node base image was recently updated causing builds to fail
during installation of redoc. Once the issue described at
https://github.com/Redocly/redoc/issues/1442 is resolved, this
change should be reverted.

Change Dockerfiles to use Node LTS

---

_includes/community/left_sidebar.html
community/error_handling_best_practices.md

This change adds the "Error Handling in libsplinter" document which
describes a set of best practices when implementing error types in
libsplinter.
Signed-off-by: Peter Schwarz <pschwarz@bitwise.io>

Add Error handling in libsplinter doc

---

community/planning/roadmap.md

Adds some content describing the suitability and focus for the v0.6 and
v0.8 releases.
Signed-off-by: Shawn T. Amundson <amundson@bitwise.io>

Add additional release description to roadmap page

---

_includes/community/left_sidebar.html
community/benchmarks/index.md
community/benchmarks/transact_db_backends.md

This commit adds a section to community/planning that may contain benchmark information for certain subsystems of Splinter.  This includes related libraries that are central to Splinter's overall operation.
The initial benchmark included is related to Hyperledger Transact Database back-ends on various cloud and local file systems.

Add planning benchmarks

---

community/error_handling_best_practices.md

violiation --> violation
: --> ::
cab --> an
see also https://github.com/Cargill/splinter/pull/1106

Fix typos in error handling guide

---

community/planning/cylinder_jwt_authentication.md
community/planning/features.md

Adds the "Cylinder JWT Authentication" feature document to the features
section of the Splinter website.

Add Cylinder JWT Authentication doc

---

_includes/0.5/left_sidebar.html
docs/0.5/howto/configure_database_storage.md

This change adds documentation for configuring a 0.5 splinter daemon's database storage.

Add database configuration doc

---

css/custom.css

This change fixes the table spacing on the roadmap page by making all tables on the page 100% width.  This will make the tables not dependent on the content.

Fix table spacing on roadmap

---

css/custom.css
docs/0.5/howto/configuring_rest_api_authorization.md
docs/0.5/references/cli/index.md
docs/0.5/references/cli/splinter-authid-create.1.md
docs/0.5/references/cli/splinter-authid-delete.1.md
docs/0.5/references/cli/splinter-authid-list.1.md
docs/0.5/references/cli/splinter-authid-show.1.md
docs/0.5/references/cli/splinter-authid-update.1.md
docs/0.5/references/cli/splinter-authid.1.md

This change adds the RBAC documentation to the "Configuring REST API Authorization Section".
It also adds the remaining man pages for the feature.

RBAC Documentation

---

community/planning/circuit_disband.md
community/planning/circuit_purge.md
community/planning/features.md
docs/0.5/references/api/openapi.yml
docs/0.5/references/cli/splinter-circuit-disband.1.md
docs/0.5/references/cli/splinter-circuit-purge.1.md
docs/0.5/references/cli/splinter-circuit-show.1.md
docs/0.5/references/cli/splinter-registry-add.1.md
docs/0.5/references/cli/splinter.1.md
docs/0.5/references/cli/splinterd.1.md

This PR adds feature documents for the `circuit-disband` and `circuit-purge` features. Also, adds the documents generated by the command `just copy-docs` which pulls in the `splinter-circuit-purge` CLI man page, as well as other updates from Splinter man pages and OpenAPI spec.

Add feature docs for `circuit-disband` and `circuit-purge`

---

community/planning/circuit_disband.md
community/planning/circuit_purge.md

Removes the empty 'Unresolved Questions' section of the `Circuit
Disband` and `Circuit Purge` feature documents. Feature documents do not
have as rigid a format, so this empty section may be omitted.

Remove disband & purge feature doc empty sections

---

community/planning/circuit_abandon.md
community/planning/circuit_disband.md
community/planning/circuit_purge.md
community/planning/features.md
docs/0.5/references/cli/splinter-circuit-abandon.1.md
docs/0.5/references/cli/splinter-circuit-disband.1.md
docs/0.5/references/cli/splinter-circuit-purge.1.md
docs/0.5/references/cli/splinter.1.md

Adds a feature doc for the `circuit-abandon` feature and adds the `splinter-circuit-abandon` man page and updates to the related man pages.

Add Circuit-Abandon feature document

---

community/planning/roadmap.md

This change adds a link to the database configuration how-to for both the PostgreSQL and SQLite rows in the 0.6 feature table.

Add DB configuration reference to roadmap

---

docs/0.4/examples/gameroom/index.md
docs/0.4/howto/building_splinter.md
docs/0.5/examples/gameroom/index.md
docs/0.5/howto/building_splinter.md

cargo build expects feature arguments slightly different than cargo deb.

Update docs with correct CARGO_ARGS information

---

.github/workflows/ci.yaml
.github/workflows/publish-docker.yaml

The Splinter project is working to transition from Travis CI to
GitHub Actions.

Add GitHub Actions workflow files

---

community/planning/features.md
community/planning/proposal_removal.md
docs/0.5/references/cli/index.md
docs/0.5/references/cli/splinter-circuit-propose.1.md
docs/0.5/references/cli/splinter-circuit-remove-proposal.1.md
docs/0.5/references/cli/splinterd.1.md

This PR updates the man pages based on the `just copy-docs` command. Also adds the feature doc for `proposal-removal`.

Add the feature doc for `proposal-removal`

---

docs/0.4/howto/building_splinter.md
docs/0.5/howto/building_splinter.md

There are a number of libraries unlikely to be present on reader's
systems that must be installed before `cargo build` will successfully
build the project. These changes clarify prerequisites so that readers
following the build instuctions can successfully build the project
without hitting roadblocks or guessing Splinter's dependencies.
Signed-off-by: Lee Bradley <bradley@bitwise.io>
Related PR: https://github.com/Cargill/splinter/pull/1347

Add prerequisites to build instructions

---

releases/0.5/download.md

The installation commands will fail with "Permission denied" if they're
run without superuser privileges.

Add missing sudo to apt install commands

---

docs/0.5/references/cli/index.md

Adds all man pages that exist but where not previously in the index -- including experimental subcommands.

Update man page index

---

community/planning/features.md
community/planning/oauth_profile.md

Add a feature doc for the `oauth-profile` feature and add it to the
features page.

Add Oauth Profile feature doc

---

community/planning/roadmap.md

This change updates the `Circuit Deletion` feature in the roadmap to
point to the currently implemented commands that allow for deleting a
circuit.

Update `Circuit Deletion` in roadmap

---

community/planning/roadmap.md

Basic metrics are currently under development as the 'metrics' feature
in libsplinter and the daemon. Since these will likely be stabilized
prior to 0.6 release, adding them to the roadmap.

Add "Basic Metrics" feature to roadmap

---

docs/0.5/references/api/openapi.yml
docs/0.5/references/cli/splinter-authid-list.1.md
docs/0.5/references/cli/splinter-circuit-propose.1.md
docs/0.5/references/cli/splinter-keygen.1.md
docs/0.5/references/cli/splinter-role.1.md
docs/0.5/references/cli/splinter-upgrade.1.md
docs/0.5/references/cli/splinter-user-list.1.md
docs/0.5/references/cli/splinter.1.md
docs/0.5/references/cli/splinterd.1.md

Update docs for 0.5.8 release

---

community/planning/features.md
community/planning/libsawtooth_receipt_store.md

Add a feature doc to the community > planning > feature section of
splinter.dev for the libsawtooth receipt store trait.

Add libsawtooth receipt store feature doc

---

css/custom.css
docs/0.5/tutorials/configuring_splinter_nodes_with_docker.md

To support service-args that are not wrapped in json list,
the default formatting for the argument has changed. To be
backwards compatibly with 0.4, the service args value needs
to be explicitly set in a json list.
Also mentions --compat 0.4 for circuits compatible with 0.4.
Commit rearranges the options a little bit to make the note look
better.
Finally adds css for blockquotes:

Add Note about required format for service args with 0.4 node

---

docs/0.5/howto/using_circuit_templates.md

Updates formatting and updates outdated information.
The updates includes:
- gameroom template to include version
- into_builders is now apply_to_builder
- link to `splinter circuit template arguments` command

Update Using Circuit Templates documentation

---

community/planning/features.md
community/planning/transact_sql_merkle_state.md

This change adds a feature doc describing details of the transact merkle state in SQL implementation.

Add Transact Merkle State in SQL feature doc

---

_includes/releases/left_sidebar.html
releases/0.6/index.md

This change adds a release page for the 0.6 release.  It includes a set of highlights and short descriptions of the major changes included in the release.

Add release page for 0.6

---

docs/0.6/tutorials/configuring_splinter_nodes_with_docker.md

Update the Configuring Two Splinter Nodes With Docker walkthrough for 0.6 docs
- fix formatting for a link
- update the example logs

Update configuring splinter nodes with docker 0.6

---

apache/rewrite.conf
ci/website.dockerfile
docker/splinter-docs-apache

Having the rewrite rules in a single shared file ensures that the latest
updates are always in the environment used for development as well as the
deployable docker image.
This change also removes the need for potentially complicated escaping
required when using "echo >".

Move Apache rewrite rules out of Dockerfiles

---

docs/0.6/concepts/splinter_certificates.md
docs/0.7/concepts/splinter_certificates.md

Update reference to `ca_certs` in the splinterd config file to
`tls_ca_file`. Additionally, update two broken links.

Update Splinter Certificates docs for 0.6 and 0.7

---

docs/0.6/howto/installing_splinter_on_ubuntu.md

Note, the use of `--group` doesn't exist in the current debs but is part of the 0.6 release.

Permissions corrections on "howto/installing_splinter_on_ubuntu"

---

_includes/releases/left_sidebar.html
releases/0.6/testing.md

This includes both an overview of the LR tests and the
Grid backwards compatibility test.
The backwards compat test is the process that has been used to
verify that Grid and Splinter 0.4 and Splinter 0.6 are compatible.
This process is put up with all current hacks to be able
to do the test locally (instead of requiring docker).
In the future this hacks may not be required.

Add a Testing document to the 0.6 release information

---

releases/0.6/download.md

Adds the correct apt URL.
Also Removes nightly and experimental apt instructions because these packages
are not currently being produced.

Update 0.6 download page

---

community/planning/features.md
community/planning/ids_as_rust_structs.md

This feature doc proposes introducing a struct for circuit and service
identifiers to replace the current use of strings.

Add "Circuit and Service Identifiers as Rust structs"

---

_includes/0.7/left_sidebar.html
docs/0.7/howto/state_delta_websockets.md
docs/0.7/index.md

Add documentation to describe how to subscribe to state delta events by
using the scabbard /ws/subscribe endpoint.
Signed-off-by: Lee Bradley <bradley@bitwise.io>

Add state delta subscription via websockets

---

community/planning/features.md
community/planning/trait_adapter_pattern.md

A pattern for using a trait with a domain-specific generic parameter
such as Trait<Item = A> in code which instead operates on a different
type such as Trait<Item = B> by constructing Trait<Item = B> as an
adapter to Trait<Item = A>.

Add design doc for Trait Adapter Pattern

---

css/custom.css

With this being included, {:.centered} can be added
at the end of an image to center the img.
for example:
"Lifecycle Integration with Admin Service"){:.centered}

Add css for img.centered

---

docs/0.6/howto/configure_logging.md

Updating the root logger to have the 'Warn' level as well as updating the other
included loggers with the 'splinter' and 'splinterd' names and `Info` levels to
match splinterd.
Signed-off-by: Caleb Hill <hill@bitwise.io>

Update the default values in the logging docs

---

community/planning/features.md
community/planning/scribe_for_scabbard_v0.7.md

Add the beginning of a scribe design doc with the mermaid sequence
diagram for scribe.

Add a scribe design doc

---

community/planning/features.md
community/planning/splinter_v0.7_database.md

New tables are covered, both for Scabbard generally and for consensus.
Included mermaid diagrams and schema doc for diesel, postgresql, and
sqlite.

Add database design doc for Splinter v0.7

---

community/planning/splinter_v0.7_database.md

- update `consensus_2pc_update_context_action_participant` to have the right primary key
- add the new scabbard store view
- remove the future work section

Update splinter db doc

---

docs/0.7/concepts/biome_user_management.md

The biome user management doc used the wrong method in the "logging out"
example. This commit updates the example from `POST /biome/logout` to
`PATCH /biome/logout`.

Fix error in biome user management doc
