docs/faq/faq.md
=> Add FAQ on running behind firewall without an open port

docs/howto/smart_contract_upload.md
Signed-off-by: Ryan Banks <rbanks@bitwise.io>
=> Add contract upload tutorial

docs/index.md
=> Add doc link to new deployment planning topic

docs/howto/uploading_smart_contract.md
=> Remove my-circuit from upload doc

docs/upgrading/splinter-v0.3.12-from-v0.3.11.md
The scabbard upload command has been moved and its parameters have been
changed slightly; this breaking change is documented here.
=> Add upgrade documentation for scabbard upload

docs/upgrading/splinter-v0.3.12-from-v0.3.11.md
=> Add scabbard upload change to 0.3.12 upgrade doc

docs/concepts/why_splinter.md, docs/index.md
This PR adds initial content to explain Splinter's benefits and key concepts.
=> New Why Splinter topic

docs/concepts/about_canopy.md
- Update and expand topic with current Canopy information and intended functionality.
- Add information about the CanopyJS and SaplingJS libraries.
- Add link to Grid UI example application.
- Change the note ("some items are not yet implemented") to a disclaimer.
=> Rewrite About Canopy topic

ci/publish-docker
=> Fix typo in dockerhub publish script

docs/concepts/about_biome.md, docs/glossary/glossary.md, docs/index.md
Adds about_biome.md and adds a definition of biome to the glossary.
=> Add initial biome content

docs/upgrading/README.md, docs/upgrading/splinter-v0.3.15-from-v0.3.14.md
Signed-off-by: Ryan Banks <rbanks@bitwise.io>
=> Add upgrade doc for upgrading from 0.3.14 to 0.3.15

api/openapi.yml
=> Update openapi.yml for 0.3.15 release

docs/upgrading/splinter-v0.3.15-from-v0.3.14.md
=> Fix broken link to heading anchor

api/openapi.yml, docs/howto/generating_insecure_certificates_for_development.md, docs/howto/uploading_smart_contract.md
=> Update protocol prefix for TLS transport to tcps://

docs/howto/generating_insecure_certificates_for_development.md
Updates the document for changes from
https://github.com/Cargill/splinter/pull/711
=> Update generating cert docs for removal of --transport

api/openapi.yml
=> Update openapi.yml for 0.3.16 release

docs/upgrading/README.md, docs/upgrading/splinter-v0.3.16-from-v0.3.15.md
=> Add upgrading doc for v0.3.16 from  v0.3.15

docs/upgrading/splinter-v0.3.17-from-v0.3.16.md
=> Add upgrading doc for v0.3.17

api/openapi.yml
=> Update openapi.yml for 0.3.17 release

docs/upgrading/splinter-v0.3.17-from-v0.3.16.md
=> Fix broken link (anchor tag) in 0.3.17 upgrade doc

_includes/header.html, _includes/right_sidebar.html, _includes/sidebar.html, _layouts/default.html
This adds initial navigational elements using bootstrap. The
navigational elements (the specific items) are examples only and
are expected to be adjusted.
Note: This is incremental, and not the final navigation work, thus there are many "known issue" such as how scrolling works. No theming has been applied yet.
To view, do "docker-compose up" and point your browser at http://127.0.0.1:4000/docs/concepts/why_splinter.html .
=> Add initial navigational elements

docs/glossary/glossary.md
=> Remove extra hyphen from two-phase commit

api/openapi.yml
=> Update openapi.yml for 0.3.18 release

_includes/header.html, css/custom.css
Adds navbar, link, and dropdown styling for the website
=> Add styling for the navbar

_includes/header.html, _includes/left_sidebar.html, _includes/right_sidebar.html, _includes/scripts.html, _includes/sidebar.html, _layouts/default.html, _layouts/landing_page.html, css/custom.css
- Organizes and cleans up some of the website code
- Adds some basic position styling for the main content
- Adds JS for dynamically determining which nav links are active
=> Website organization

_includes/left_sidebar.html, _includes/scripts.html, css/custom.css
Dynamically sets active version in version dropdown, and adds custom styling for `<code>` elements.
=> Dynamic version dropdown

docs/0.4/references/api/openapi.yml
=> Update openapi.yml for 0.3.19 release

_layouts/default.html, _layouts/landing_page.html, _layouts/sidebars.html, css/custom.css
=> Keep footer at the bottom of the window on short pages

community/index.md
=> Add info + link for engineering forum

_includes/0.4/left_sidebar.html, _includes/0.5/left_sidebar.html
=> Fix CLI entry in left-sidebar TOC

docs/gameroom_walkthrough/act_1/behind_the_scenes/behind_scene_1.md, docs/gameroom_walkthrough/act_1/behind_the_scenes/images/auth_login_acme1.svg, docs/gameroom_walkthrough/act_1/behind_the_scenes/images/auth_login_acme3.svg, docs/gameroom_walkthrough/act_1/behind_the_scenes/images/auth_login_acme4.svg, docs/gameroom_walkthrough/act_1/behind_the_scenes/images/auth_login_acme5.svg
Updates the Act 1, Scene 1 of the gameroom walkthrough so it is up to date with the 0.4 version of Splinter.
=> Update act 1, scene 1 to 0.4

releases/splinter_0_4_release_overview.md
Note that the links to splinter.dev won't work until the real website is live.
=> Add Splinter v0.4 release overview

docs/0.4/references/api/openapi.yml
=> Update openapi.yml for 0.4.0 release

404.md, _layouts/404.html, css/custom.css
=> Add custom 404 page for the website

_includes/head.html, css/custom.css
This PR adds the appropriate headers to trigger the responsive behaviour of bootstrap, and makes a minor change to the landing page to improve its look on mobile devices.
=> Update the docs to be mobile friendly

docs/0.4/concepts/biome_user_management.md, docs/0.5/concepts/biome_user_management.md, docs/images/biome_architecture_diagram.svg, docs/images/biome_database_schema.svg
Add detailed Biome overview, architecture diagram, examples, and reference info
=> Expand About Biome topic

docs/0.5/concepts/biome_user_management.md
Bug fix: This PR adds the final two reviewer changes from PR 39 (which skipped the 0.5 changes by mistake).
=> Make 0.5 Biome doc match the current 0.4 version

_includes/releases/left_sidebar.html, releases/0.4/download.md
=> Add 0.4 release download page

_includes/community/left_sidebar.html, community/repositories.md, releases/0.4/download.md
Also add link to this list in Releases > Download
=> Add list of Splinter repos to Community

_includes/community/left_sidebar.html, community/planning/canopy_0.2.md, community/planning/features.md, images/canopy_0.2_overview.svg
Note, let's not use this PR to discuss the design being added here.  We can continue to iterate on it in future PR's.  This mainly is a design doc to help bootstrap the planning features section of the documentation.
=> Add Community Feature Planning section

css/custom.css, docs/0.4/examples/gameroom/walkthrough/index.md, docs/0.5/examples/gameroom/walkthrough/index.md
Moves the Gameroom walkthrough intro, which was all of the pertinent material before the first act.
=> Move Gameroom Walkthrough introduction

css/custom.css, docs/0.4/glossary/glossary.md, docs/0.5/glossary/glossary.md
=> Add glossary theming

docs/0.4/howto/planning_splinter_deployment.md, docs/0.5/howto/planning_splinter_deployment.md
=> Fix FAQ link in deployment planning doc

community/planning/features.md, community/planning/peer_manager.md, css/custom.css, images/canopy_0.2_overview.svg, images/peer_manager_connection.svg, images/peer_manager_dep.svg, images/peer_manager_reconnection.svg, images/peer_manager_reconnection_endpoint.svg
The feature doc is currently made up of a high level
description, a dependency graph, and sequence diagrams
for connecting/reconnecting to peers.
This doc will be expanded in the future.
=> Add the intitial PeerManager feature doc

docs/0.4/examples/gameroom/walkthrough/index.md, docs/0.5/examples/gameroom/walkthrough/index.md
Updates scene 2 to match details in 0.4 Splinter.
=> Update scene 2 in gameroom walkthrough

_includes/scripts.html, css/custom.css, scripts/generateRightSidebar.js, scripts/manPage.js
Update the following: 
- removes the % SPLINTER(1) Cargill, Incorporated.. line
- Updates the document.title to match the command
- Adds a h1 for the command
- Updates section titles so they are not all letters are capital
- Removes the last SEE ALSO section
- Adds special handling for adding a right sidebar
=> Reformat Manpages

community/planning/admin_service_store.md, community/planning/features.md, images/admin_store_routing.svg
=> Add design document for Admin Service Store and Routing Table

community/planning/admin_service_store.md
=> Fix formatting of traits in Admin Service Store

docs/0.4/references/api/openapi.yml
=> Update openapi.yml for 0.4.1 release

community/planning/admin_service_store.md
Update the doc to more closely match the traits that have
been implemented in splinter.
Also updates a typo where Writer should have been Reader.
=> Update traits described in Admin Service Store doc

_config.yml, _includes/analytics.html, _includes/head.html, ci/publish-docker, ci/website.dockerfile
Analytics are disabled for development and testing, but will be included
during CI builds of the deployable Docker image.
=> Add Google Analytics

community/index.md
=> Update engineering forum information

docs/0.4/tutorials/using_the_admin_ui.md, docs/0.5/tutorials/using_the_admin_ui.md
The compose file was moved to the root of the repository to simplify running
compose commands.
=> Update admin-ui tutorial compose commands

community/index.md
=> Add link on community page to slack inviter

community/planning/cylinder_jwt.md, community/planning/features.md
This PR adds the design/RFC for the Cylinder JWT module.
=> Add Cylinder JWT design

community/planning/biome_oauth_user_store.md, community/planning/features.md, community/planning/oauth2_rest_api_authentication.md
This change adds the Biome OAuth integration design to the community
feature planning section.
Signed-off-by: Peter Schwarz <pschwarz@bitwise.io>
=> Add Biome OAuth Integration design

docs/0.4/concepts/security_considerations.md, docs/0.4/howto/hosting_a_splinter_node.md, docs/0.4/howto/planning_splinter_deployment.md, docs/0.4/howto/uploading_smart_contract.md, docs/0.4/tutorials/configuring_splinter_nodes.md, docs/0.5/concepts/security_considerations.md, docs/0.5/howto/hosting_a_splinter_node.md, docs/0.5/howto/planning_splinter_deployment.md, docs/0.5/howto/uploading_smart_contract.md, docs/0.5/tutorials/configuring_splinter_nodes.md
Update to include the latest on auth support for the splinterd REST API
=> Update REST API security details

.travis.yml
=> Update CI to publish Docker image during main branch builds

_includes/0.5/left_sidebar.html, docs/0.5/concepts/security_considerations.md, docs/0.5/howto/configuring_rest_api_authorization.md
Adds a document that describes how to configure authentication and authorization for the Splinter REST API.
Also updates the security considerations document to describe the auth capabilities of the REST API and link to the auth document.
=> Auth configuration tutorial

community/planning/capabilities-repository.md, community/planning/features.md
This change adds the initial proposal for the splinter artifact  repository layout and tools. It covers the requirements for saplings and smart contracts, as well as introduces the concept of a Capability.
A Capability is a distribution of other artifacts that will make up a complete application.  It defines a set of dependencies that include smart contracts and saplings, though may include additional plugin components, such as state delta export processors and CLI tools.
[Rendered](https://github.com/peterschwarz/splinter-docs/blob/repository-design/community/planning/capabilities-repository.md)
=> Add splinter repository design

community/planning/features.md, community/planning/rest_api_authorization.md, community/planning/rest_api_maintenance_mode.md, docs/0.5/concepts/security_considerations.md
Some minor updates to security documentation
=> Security docs updates

docs/0.5/tutorials/configuring_splinter_nodes.md
Updates the "Configuring Two Splinter Nodes" tutorial to include
instructions for setting up the allow keys file to grant permissions to
the user keys.
=> Add allow_keys config to node config doc

_includes/releases/left_sidebar.html, releases/0.5/download.md, releases/0.5/index.md
=> Add 0.5 download page with extraball apt repo info

community/planning/challenge_authorization.md
This update includes removing the lists of authorization types
and multiple public keys, removed explicit versions from the
authorization types, added multiple public key/signatures
to the challenge submit requests, and updated where the public
keys are stored so they are within the circuit itself.
Also includes rational and alternatives for the changed items and
includes some small formatting changes.
=> Update Challenge Authorization features doc

docs/0.5/references/api/openapi.yml
=> Update openapi.yml for 0.5.3 release

docs/0.5/references/api/openapi.yml
=> Update openapi.yml for 0.5.4 release

.github/workflows/publish-docker.yaml
=> Export Google tokens as env vars during publishing

.github/workflows/publish-docker.yaml
=> Export correct PSE value during docker publish workflow

docs/0.5/references/api/openapi.yml
=> Update openapi.yml for 0.5.6 release

docs/0.5/references/api/openapi.yml
=> Update openapi.yml for 0.5.7 release

docs/0.5/references/api/openapi.yml
=> Update docs for 0.5.9 release

docs/0.5/howto/configuring_rest_api_authorization.md
=> Correct biome splinter CLI flag in rest-api auth doc

community/stable_feature_checklist.md
=> Add example config file updates to stabilzation checklist

docs/0.5/references/api/openapi.yml, docs/0.5/references/cli/splinter-upgrade.1.md, docs/0.5/references/cli/splinter.1.md
=> Update docs for 0.5.11 release

docs/0.5/references/api/openapi.yml
=> Update docs for 0.5.12 release

docs/0.5/references/api/openapi.yml
=> Update docs for 0.5.13 release

CODEOWNERS, MAINTAINERS.md
Also updates retired maintainers
=> Add Caleb Hill and Lee Bradley as maintainers 

.github/workflows/ci.yaml
=> Trigger builds at 10am UTC

community/stable_feature_checklist.md
=> Add bash completion updates to stabilzation checklist

docs/0.5/references/api/openapi.yml, docs/0.5/references/cli/splinter-keygen.1.md, docs/0.5/references/cli/splinter-upgrade.1.md, docs/0.5/references/cli/splinterd.1.md
=> Update docs for 0.5.17 release

community/planning/features.md, community/planning/scabbard_back_pressure.md
=> Add feature doc for Scabbard Back Pressure

docs/0.5/references/api/openapi.yml
=> Update docs for 0.5.18 release

docs/0.5/concepts/splinter_registry.md
also fixes an outdated link to REST API spec
=> Clarify local registry is stored in splinterd database

docs/0.5/references/api/openapi.yml, docs/0.5/references/cli/splinterd.1.md
=> Update docs for 0.5.20 release

docs/0.5/references/api/openapi.yml, docs/0.5/references/cli/scabbard-contract-upload.1.md
=> Update docs for 0.5.23 release

docs/0.5/references/api/openapi.yml
=> Update docs for 0.5.24 release

_includes/0.5/left_sidebar.html, docs/0.5/concepts/application_authorization.md
This documentation is based on the existing documentation in the
gameroom walkthrough.
=> Add Application Authorization documentation

docs/0.5/references/cli/index.md
=> Correct link for splinter circuit disband

docs/0.5/howto/generating_insecure_certificates_for_development.md
=> Small updates for generating certificates documentation

docs/0.5/references/api/openapi.yml
=> Update docs for 0.5.26 release

docs/0.6/howto/configuring_rest_api_authorization.md
Update the the "Configuring REST API Authorization" page for 0.6 docs
=> Update Configuring REST API Authorization 0.6

_includes/releases/left_sidebar.html, releases/0.6/upgrading/README.md, releases/0.6/upgrading/splinter-v0.6-from-v0.4.md
This document contains important notes on breaking
features and required updates.
=> Add upgrading doc for 0.6 from 0.4

docs/0.6/concepts/biome_user_management.md, docs/0.6/images/biome_database_schema.svg, docs/0.7/concepts/biome_user_management.md, docs/0.7/images/biome_database_schema.svg
Update the Biome User Management 0.6 and 0.7 docs
- update content to reflect the current submodules in the biome module and the current biome REST API endpoints
- add an updated diagram for the biome database tables
=> Update Biome User Management 0.6 and 0.7

docs/0.6/references/api/openapi.yml
=> Update docs for 0.6.1 release

docs/0.6/references/cli/index.md, docs/0.7/references/cli/index.md
=> Fix splinter upgrade link on cli index

_data/general.yml, _includes/0.4/left_sidebar.html, _includes/0.6/left_sidebar.html, _includes/0.7/left_sidebar.html, _includes/releases/left_sidebar.html, docs/index.md, releases/index.md, search/index.md
- Update /releases/ sidebar
- Update /docs/ version selector
- Update search page links
- Update redirects in /releases/index.md and /docs/index.md
- Update version in data/general.yml
=> Update website to show that v0.6 has been released

community/planning/roadmap.md
=> Update 0.6 Roadmap

community/planning/features.md
=> Move completed feature docs to Historical

docs/0.6/references/api/openapi.yml
=> Update docs for 0.6.7 release

docs/0.4/index.md, docs/0.6/index.md, docs/0.7/index.md
=> Update link to Sawtooth Events documents

community/planning/echo_service_design.md, community/planning/features.md
Add the design document for the echo service to the community/planning section of the splinter website
=> Echo service design doc

CODEOWNERS, MAINTAINERS.md
=> Add Isabel Tomb to MAINTAINERS and CODEOWNERS

community/planning/echo_service_design.md
Add links to the other design docs related to the service API.
=> Add links to echo service design doc

docs/0.6/references/api/openapi.yml, docs/0.6/references/cli/splinter-state-migrate.1.md
=> Update docs for 0.6.12 release

_includes/head.html, _includes/mermaid.html, css/custom.css
To add a diagram, add the following Jekyll front matter to the
top of the page:
---
tags: [Mermaid]
mermaid: true
---
Next, add the mermaid syntax wrapped in a <div class="mermaid">:
<div class="mermaid">
graph LR
1 --- 2
2-->A[foo]
2-->B(bar)
</div>
=> Add files to generate mermaid diagrams

docs/0.6/references/api/openapi.yml
=> Update docs for 0.6.13 release

community/planning/publisher_for_scabbard_v0.7.md
Adds sequence diagrams for Finalizing and Canceling publishing artifacts, as well as the interaction between BatchVerifier and Transact components. 
Build on #323
=> Publisher seq diagrams

CODEOWNERS, MAINTAINERS.md
Signed-off-by: Amelia Bradley <bradley@bitwise.io>
=> Update maintainer name

community/planning/splinter_v0.7_database.md
Update the splinter database feature doc for changes in the scabbard store
=> Update splinter database feature doc

community/planning/splinter_v0.7_database.md
- Update the splinter database feature doc for the changes made in scabbard store to support the addition of `decision_ack` in consensus
- Update the splinter database feature doc for future structural changes that are going to be made to scabbard store
=> Update splinter database doc for scabbard store changes

community/planning/splinter_v0.7_database.md
Design associated with https://github.com/Cargill/splinter/pull/2027
=> Add Supervisor notification database documentation

community/planning/consensus_runner.md, community/planning/features.md
This change adds the ConsensusRunner design to the set of features in the community planning section.
=> Add ConsensusRunner design

docs/0.6/references/api/openapi.yml, docs/0.6/references/cli/splinterd.1.md
=> Update docs for 0.6.14 release

_includes/0.7/left_sidebar.html, docs/0.7/howto/running_echo_service.md
Add a doc on how to run the echo service
=> Add How to run echo service 0.7 doc

docs/0.7/howto/removing_a_splinter_circuit.md, docs/0.7/howto/running_echo_service.md, docs/0.7/howto/uploading_smart_contract.md
=> 0.7 Doc updates
